version: '3.4'

services:
  mariadb:
    container_name: blog-mariadb
    build:
      context: ./db
      target: client_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - blog-data:/var/lib/mysql
    ports:
      - "3212:3306"

  php:
    container_name: blog-php-apache
    build:
      context: ./php
      target: client_php
    volumes:
      - ../:/srv
      - ./.env:/srv/.env
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - '8766:80'

volumes:
  blog-data: {}
